spring.application.name=company-ai

spring.datasource.url=jdbc:mysql://localhost:3306/company_ai
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

nvidia.api.key=${NVIDIA_API_KEY}
nvidia.api.url=https://integrate.api.nvidia.com/v1/chat/completions
nvidia.model=openai/gpt-oss-20b

nvidia.embedding.url=https://integrate.api.nvidia.com/v1/embeddings
nvidia.embedding.model=nvidia/nemotron-3-embed-1b

qdrant.url=https://6f5c5d5c-1cdc-4acb-8b69-2ff6f20a826b.eu-central-1-0.aws.cloud.qdrant.io:6333
qdrant.api.key=${QDRANT_API_KEY}